### ISSUE TITLE
Error in run.sh+ failed to launch

### ISSUE THREAD

**Issue by Lerenn** [desertbit/docker-owncloud#1]
I'm very interested by your version of owncloud docker, but I have a little problem.
The run script seems to have a problem.
Have I done something wrong ?

> \# docker run -d --name oc -p 80:80 desertbit/owncloud
5d0e3b2171c5fe811b4d4be6642fff617fbe29c0937aa1fd8f10b75b6cd221be
> \# docker logs oc
Setting timezone to UTC... Done !
/usr/bin/run.sh: line 75: : command not found
Creating autoconfig.php... 
> \# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Thank you !

**Comment by m4ng0squ4sh** [comment]
Thank you for reporting this issue. This was a small mistake which was pushed with the last commit.
I fixed this issue, updated ownCloud to the latest release and added some more setup information to the README.

A simple pull will get things going for you:
```bash
docker pull desertbit/owncloud
```
